### ISSUE TITLE
Broken with Paraview 5.8

### ISSUE THREAD

**Issue by CharlesGueunet** [topology-tool-kit/ttk#373]
**Describe the bug**
TTK does not compile with ParaView 5.8 anymore

**To Reproduce**
When trying to compile TTK with ParaView 5.8:

```
In file included from /home/charles/Software/compil/ttk-charles/core/vtk/ttkAlgorithm/ttkAlgorithm.cpp:5:
/home/charles/Software/compil/ttk-charles/core/vtk/ttkAlgorithm/ttkAlgorithm.cpp: In static member function ‘static ttkOnDeleteCommand* ttkOnDeleteCommand::New()’:
/home/charles/Software/compil/ttk-charles/core/vtk/ttkAlgorithm/ttkAlgorithm.cpp:62:1: error: invalid static_cast from type ‘vtkObject*’ to type ‘ttkOnDeleteCommand*’
   62 | vtkStandardNewMacro(ttkOnDeleteCommand);
      | ^~~~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
gmake[2]: *** [../build/core/vtk/ttkAlgorithm/CMakeFiles/ttkAlgorithm.dir/build.make:83: ../build/core/vtk/ttkAlgorithm/CMakeFiles/ttkAlgorithm.dir/ttkAlgorithm.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:11589: ../build/core/vtk/ttkAlgorithm/CMakeFiles/ttkAlgorithm.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
```

**System:**
 - OS: Gentoo
 - Compiler GCC 9.3.0
 - TTK current dev branch
 - PV master

**Comment by CharlesGueunet** [comment]
I am currently testing with 5.8

**Comment by CharlesGueunet** [comment]
The issue is only with ParaView master, not 5.8.
